### ISSUE TITLE
respx fails to build with Python 3.10

### ISSUE THREAD

**Issue by fabaff** [lundberg/respx#135]
There is a build failure with Python 3.10:

```bash
TypeError: traceback_exception_init() got an unexpected keyword argument 'compact'
```

For the full details please check https://bugzilla.redhat.com/show_bug.cgi?id=1927699

Thanks

**Comment by lundberg** [comment]
Thanks for reporting. Gave a quick look, and the stack trace smells tests 3:rd party issue, i.e. `trio` (?).

**Comment by lundberg** [comment]
I marked the `TrioBackend` test case to be skipped on `3.10` for now, seems to solve this issue.

@fabaff please verify, and I'll merge #137.

**Comment by tirkarthi** [comment]
trio has an issue on this : https://github.com/python-trio/trio/issues/1899

**Comment by hrnciar** [comment]
Hello, I can confirm respx builds with Python3.10 with this patch until trio is fixed. Thank you.

https://copr.fedorainfracloud.org/coprs/g/python/python3.10/build/2097379/
