### PR TITLE
Don't test TrioBackend on python 3.10

### LINKED ISSUE #135: respx fails to build with Python 3.10
There is a build failure with Python 3.10:

```bash
TypeError: traceback_exception_init() got an unexpected keyword argument 'compact'
```

For the full details please check https://bugzilla.redhat.com/show_bug.cgi?id=1927699

Thanks

### PR DESCRIPTION
**Pull request by lundberg**
Fixes #135

### CODE REVIEW

**Comment by lundberg** [comment]
Re-opening and re-adding trio test for python 3.10...renaming PR.
