### ISSUE TITLE
module 'respx' has no attribute 'pop'

### ISSUE THREAD

**Issue by paulineribeyre** [lundberg/respx#70]
Hello- I am trying to use the `pop` method as described in the docs (https://github.com/lundberg/respx/pull/60), but running into the issue below. As you can see I am using the latest version, which should include `pop`:

```
    @respx.mock
    def test_something():
        import pkg_resources
        assert pkg_resources.get_distribution('respx').version == "0.12.1"
    
        respx.get("https://foo.bar/", status_code=404, alias="index")
>       request_pattern = respx.pop("index")
E       AttributeError: module 'respx' has no attribute 'pop'
```

Is there something I'm doing wrong?

**Comment by lundberg** [comment]
Nope, you're right....seems like the global API is missing `pop`, i.e. docs is incorrect.

The `pop` feature introduced in #60 is currently only available through a mock transport instance...

```py
@respx.mock()
def test_something(respx_mock):
    ...
    respx_mock.pop("index")
```

It's an easy fix to expose it globally in `api.py`, thanks for finding and reporting the issue!

**Comment by paulineribeyre** [comment]
@lundberg thanks for having a look, I made a PR to fix this: https://github.com/lundberg/respx/pull/72
